spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basicauthentification?createDatabaseIfNotExist=true #&autoReconnect=true&useSSL=true&useUnicode=yes&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: PasSw@rd2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: javacigma@gmail.com
    password: vnjilnngkccngdsm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# App Properties
cle:
  privite:
    securite: tidili@MtI2023

delai:
  expiration: 86400000

server:
  port: 8091
  
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  file:
    name: app.log  
 
